name: credpal_assessment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/product_images/
    - assets/images/vendor_images/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Light.otf
          weight: 300
        - asset: assets/fonts/AvenirLTStd-LightOblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 400
        - asset: assets/fonts/AvenirLTStd-BookOblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/AvenirLTStd-Roman.otf
          weight: 400
        - asset: assets/fonts/AvenirLTStd-Oblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/AvenirLTStd-Medium.otf
          weight: 500
        - asset: assets/fonts/AvenirLTStd-MediumOblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/AvenirLTStd-Heavy.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-HeavyOblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 900
        - asset: assets/fonts/AvenirLTStd-BlackOblique.otf
          weight: 900
          style: italic
